### ISSUE TITLE
compiling for test .....

### ISSUE THREAD

**Issue by xgnusr** [Funatiq/cuclark#3]
Installing cuCLARK, cuCLARK-l and programs for target definition in folder ./exe/

make -C src
make[1]: se entra en el directorio '/xgn/ubioma/cuclark/src'
nvcc  -arch=sm_30 -O3  -Xcompiler -fopenmp -o cuCLARK CuClarkDB.cu main.cc analyser.cc file.cc kmersConversion.cc
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
Makefile:27: fallo en las instrucciones para el objetivo 'cuCLARK'
make[1]: *** [cuCLARK] Error 1
make[1]: se sale del directorio '/xgn/ubioma/cuclark/src'
Makefile:8: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

Any idea ??
Thanks in advance !!

**Comment by Funatiq** [comment]
Please try to uncomment the `-D_FORCE_INLINES` flag (remove the `#`) in line 3 of [the Makefile](https://github.com/Funatiq/cuclark/blob/master/src/Makefile).
You can also upgrade to CUDA 8 where this issue should be resolved.
