### ISSUE TITLE
"CUERR 'invalid device pointer'"

### ISSUE THREAD

**Issue by imet-k** [Funatiq/cuclark#4]
It crash when processising the file with "CUERR 'invalid device pointer' line 311 message.
---------------------------------------------------------
 ./exe/cuCLARK -D ./DIR_DB/ -T ./DIR_DB/targets.txt -O CW2488_L001_R1.fasta -R result
-----------------------------------------------------------------------------------------
CuCLARK version 1.1 (Copyright 2016 Robin Kobus, rkobus@students.uni-mainz.de)
Based on CLARK version 1.1.3 (UCR CS&E. Copyright 2013-2016 Rachid Ounit, rouni0                                                                             01@cs.ucr.edu)
Starting the creation of the database of targets specific 31-mers from input fil                                                                             es...
 Progress report: (18987/18987)    496238623 nt read in total.
Mother Hashtable successfully built. 201281453 31-mers stored.
Hashtable sorting done: maximum number of collisions: 6
Removal of common k-mers done: 176967365 specific 31-mers found.
Creating database in disk...
176967365 31-mers successfully stored in database.
Checking for CUDA devices: 2 device(s) found.
Device 0 = GeForce GTX 1080 Ti
Device 1 = GeForce GTX 1080 Ti
Enabling peer access between devices 0 and 1
Loading database [./DIR_DB//db_central_k31_t7374_s1610612741_m0.tsk.*] (s=1)...
Total DB size in RAM:   7.504 GB
Total device memory:    22.303 GB (800 MB reserved)
Requiring 1 loop(s).
DB loaded in RAM.
Processing file 'CW2488_L001_R1.fasta' in 1 batches using 1 CPU thread(s).
CUERR 'invalid device pointer' in CuClarkDB.cu, line 311

**Comment by Funatiq** [comment]
Hi! Can you please check if the branch
https://github.com/Funatiq/cuclark/tree/testing
fixes your issue.

**Comment by imet-k** [comment]
It fixed it. Thank you very much.
