### ISSUE TITLE
Windows port, query on set_targets.sh

### ISSUE THREAD

**Issue by prabindh** [Funatiq/cuclark#6]
I forked this to port to Windows (ie visual studio build) ? To know if the port is working correctly, what unit-test-cases can be used ? Thanks for the pointers.

**Comment by Funatiq** [comment]
You can take a look at the [README.md](https://github.com/Funatiq/cuclark/tree/master/data) in the data folder and use the example there.

**Comment by prabindh** [comment]
Yes I did, but there is no "example.sh" as mentioned in the README.

> Run the included `example.sh` to verify the output of your CuCLARK installation.

**Comment by Funatiq** [comment]
You have to download the example from the README. The script it definitely included.

**Comment by prabindh** [comment]
I misunderstood that example.sh was supposed to be part of this (ie cuclark) package. I can see the example.sh in the example_db after downloading. Thanks.

**Comment by Funatiq** [comment]
No problem. Good luck with the port.
