### ISSUE TITLE
Windows port - All confidence values 0

### ISSUE THREAD

**Issue by prabindh** [Funatiq/cuclark#7]
Continuing the Windows port (CUDA10.0), at https://github.com/prabindh/cuclark.

On running CuClark from the example_db set, I get an output .fa file, with all confidences to 0. like below. Any clues to why this could happen ?

```
$> cuclark -T custom_0_canonical -O HiSeq_accuracy.fa -R HiSeq_accuracy_output.fa -d 1
Result CSV line(s) example
A_hydrophila_HiSeq.922,101,0,NA,0,NA,0,0
```

```
Processing file '.\dataset\HiSeq_accuracy.fa' in 1 batches using 1 CPU thread(s).
Batch 0: AVG read length 93, Estimated # containers per read: 14
Estimated # containers per read: 14
Batch 0  # Containers: 128840 (AVG # per read: 12.884).
Host 0 Batch 0   CUDA start.    Read data size: 0 MB    Result data size: 0.05 MB
Batch 0 scheduled. Objects: 10000 Size: 0.297 MB
```
Full logs are at,
https://github.com/prabindh/deepnotes/tree/master/cuclark-windows

**Comment by Funatiq** [comment]
In your logs it shows that CUDA encountered an error. I am not sure what exactly went wrong. You can try to compile the debug version of CuClark to get some more hints. Take a look at the debug flags in the [Makefile](https://github.com/Funatiq/cuclark/blob/master/src/Makefile).

**Comment by prabindh** [comment]
From the initial look of the log, it appeared that the error was in the free "after" the compute, so didnt pay attention. If nothing else strikes the eye, will drill down.

**Comment by Funatiq** [comment]
Keep in mind that the CUDA error can originate from any previous asynchronous call (kernel or memcpy).
The debug version uses additional synchronization and error checking to identify the real origin of the error.
